### PR TITLE
Esra created new file

### PR DESCRIPTION
**Pull request by shahes**
Please review this blank page:)

### CODE REVIEW

**Comment by Gulira91** [comment]
great job Esra!

**Comment by CihanSaracoglu** [comment]
As you see we have a conflict here
We should not push our codes directly to the master, this is the key point while using GitHub
Everyone must have a different branch
Before we push the code to the GitHub, if we merge it to our local master, and then push it to the GitHub, we will have conflicts or everyone is gonna change the project without any pull request. Pushing the code directly from our local master is directly gonna change our remote master.
In order to prevent this issue:
1. Everyone must have a unique branch under his/her name
2. Everyone must push his/her code from this branch
We have to create a new branch in our local and we have to push our code directly from our branch to the remote origin/master

**Comment by shahes** [comment]
I think we need to do one or more git/gitHub meeting to understand the issues deeply. Still question marks in the head:)


Thank you

**Comment by AyselSari** [comment]
hi Esra

**Comment by CihanSaracoglu** [comment]
Solved the conflict

**Comment by CihanSaracoglu** [comment]
Good

**Pull request closed without merging**
